### ISSUE TITLE
Is it possible to port to Android?

### ISSUE THREAD

**Issue by Brandonv101** [aydenp/Bank#23]
Hi there,

I am wondering if it's possible to port this app over to Android or if this app can only work with iOS devices.

Thanks!

**Comment by aydenp** [comment]
Hi Brandon,

Thanks for writing in! At this point, I don't have any plans to port this app to Android. It is more of a side-project, and additionally I don't have any native Android development experience. For these reasons, it's not really feasible at the moment. However, if Android development is your forte I welcome you to take a stab at it! 

Since this repository is dedicated to the iOS Bank app specifically, I'm going to close this issue as its not specifically relevant. If you ever do decide to develop something like that, feel free to reach out to me using the email on my profile! I'd love to help answer any technical questions and link to it from the readme.
